sudo: required
services:
  - docker

before_install:
  - docker build -t ad/docker-react -f Dockerfile.dev .

script:
  - docker run ad/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-2-3030303030"
  bucket_path: "docker-react" # exactly same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
